# -*- coding: utf-8 -*-
"""DIP_FinalProject _MojtabaHashembeigi.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17Wws1AQQIVDdapNnr9Voszdcu1P2gmfJ
"""

# std_name: Mojtaba Hashenbeigi
# std_id : 4043614036



# آماده‌سازی محیط، اتصال به درایو و دانلود مدل

import os
from google.colab import drive

# ۱. اتصال به گوگل درایو
drive.mount('/content/drive')

project_path = '/content/drive/My Drive/DIP_FinalProject'
video_path = os.path.join(project_path, 'Eagle.mp4')

if not os.path.exists(project_path):
    os.makedirs(project_path)
    print(f"پوشه ایجاد شد: {project_path}")

if not os.path.exists(video_path):
    print(" خطا: فایل Eagle.mp4 در درایو یافت نشد. لطفاً آن را آپلود کنید.")
else:
    print(" فایل ویدیویی با موفقیت یافت شد.")

# Commented out IPython magic to ensure Python compatibility.
# . کلون کردن مخزن و نصب پیش‌نیازها
!git clone https://github.com/facebookresearch/sam3.git
# %cd sam3
!pip install -e .
!pip install opencv-python matplotlib numpy torch torchvision

#  دانلود وزن‌های مدل SAM 3 با aria2
!apt-get -qq install -y aria2
URL = "https://huggingface.co/bodhicitta/sam3/resolve/main/sam3.pt"
!aria2c -x 16 -s 16 -k 1M -c --file-allocation=none -o sam3.pt -d /content "{URL}"

CHECKPOINT_PATH = "/content/sam3.pt"
size_gb = os.path.getsize(CHECKPOINT_PATH) / 1e9
print(f" مدل دانلود شد: {size_gb:.2f} GB")
assert size_gb > 3.3, "خطا در دانلود مدل، لطفاً دوباره تلاش کنید."



!pip install triton einops ninja

# ردیابی ویدیویی و تولید خروجی

import os
import cv2
import numpy as np
import torch
import matplotlib.pyplot as plt
import huggingface_hub

if os.path.exists('/content/sam3'):
    os.chdir('/content/sam3')

CHECKPOINT_PATH = "/content/sam3.pt"

if getattr(huggingface_hub.hf_hub_download, '__name__', '') != 'smart_hf_download':
    original_hf_download = huggingface_hub.hf_hub_download

    def smart_hf_download(*args, **kwargs):

        if 'repo_id' in kwargs and kwargs['repo_id'] == 'facebook/sam3':
            kwargs['repo_id'] = 'bodhicitta/sam3'
        elif len(args) > 0 and args[0] == 'facebook/sam3':
            args = ('bodhicitta/sam3',) + args[1:]

        filename = kwargs.get('filename', '')
        if not filename and len(args) > 1:
            filename = args[1]

        if 'sam3.pt' in str(filename):
            return CHECKPOINT_PATH

        return original_hf_download(*args, **kwargs)

    huggingface_hub.hf_hub_download = smart_hf_download

if getattr(os.path.dirname, '__name__', '') != 'safe_dirname':
    original_dirname = os.path.dirname
    def safe_dirname(p):
        if p is None:
            return "/content/sam3"
        return original_dirname(p)
    os.path.dirname = safe_dirname
# --------------------------------------------------------

from sam3.model_builder import build_sam3_video_predictor

video_path = '/content/drive/My Drive/DIP_FinalProject/Eagle.mp4'
output_video_path = '/content/drive/My Drive/DIP_FinalProject/Eagle_tracked.mp4'

print("در حال بارگذاری مدل SAM 3...")
gpus_to_use = list(range(torch.cuda.device_count())) if torch.cuda.is_available() else []

predictor = build_sam3_video_predictor(gpus_to_use=gpus_to_use)

print("شروع نشست (Session) پردازش ویدیو...")
response = predictor.handle_request(
    request=dict(type="start_session", resource_path=video_path)
)
session_id = response["session_id"]

print("ارسال دستور متنی 'eagle' به فریم اول...")
predictor.handle_request(
    request=dict(
        type="add_prompt",
        session_id=session_id,
        frame_index=0,
        text="eagle",
    )
)

print("در حال استخراج ماسک‌ها (این مرحله روی GPU انجام می‌شود)...")
outputs_per_frame = {}
for response in predictor.handle_stream_request(
    request=dict(type="propagate_in_video", session_id=session_id)
):
    outputs_per_frame[response["frame_index"]] = response["outputs"]

predictor.handle_request(request=dict(type="close_session", session_id=session_id))
predictor.shutdown()


# پردازش تصویر و رندر ویدیوی خروجی با OpenCV
# ==========================================

print("پردازش مدل تمام شد. شروع رندر ویدیوی خروجی...")

def extract_binary_mask(frame_output, h, w):
    try:
        def find_tensor(obj):
            if isinstance(obj, torch.Tensor) or isinstance(obj, np.ndarray):
                if hasattr(obj, 'shape') and len(obj.shape) >= 2 and obj.shape[-2] == h and obj.shape[-1] == w:
                    return obj
            elif isinstance(obj, dict):
                for v in obj.values():
                    res = find_tensor(v)
                    if res is not None: return res
            elif isinstance(obj, (list, tuple)):
                for item in obj:
                    res = find_tensor(item)
                    if res is not None: return res
            return None

        found = find_tensor(frame_output)
        if found is not None:
            if isinstance(found, torch.Tensor):
                found = found.detach().cpu().numpy()
            found = np.squeeze(found)
            if found.ndim == 3: found = found[0]
            return (found > 0).astype(np.uint8) * 255
    except:
        pass
    return np.zeros((h, w), dtype=np.uint8)

cap = cv2.VideoCapture(video_path)
width  = int(cap.get(cv2.CAP_PROP_FRAME_WIDTH))
height = int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))
fps    = cap.get(cv2.CAP_PROP_FPS)

fourcc = cv2.VideoWriter_fourcc(*'mp4v')
out_video = cv2.VideoWriter(output_video_path, fourcc, fps, (width, height))

centroids_x = []
centroids_y = []
trajectory_points = []

frame_idx = 0
while True:
    ret, frame = cap.read()
    if not ret:
        break

    mask = extract_binary_mask(outputs_per_frame.get(frame_idx, None), height, width)

    M = cv2.moments(mask)
    if M["m00"] != 0:
        cX = int(M["m10"] / M["m00"])
        cY = int(M["m01"] / M["m00"])

        centroids_x.append(cX)
        centroids_y.append(cY)
        trajectory_points.append((cX, cY))

        contours, _ = cv2.findContours(mask, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
        if contours:
            c = max(contours, key=cv2.contourArea)
            x, y, w_box, h_box = cv2.boundingRect(c)

            cv2.rectangle(frame, (x, y), (x + w_box, y + h_box), (0, 255, 0), 2)
            cv2.putText(frame, "Eagle", (x, y - 10), cv2.FONT_HERSHEY_SIMPLEX, 0.7, (0, 255, 0), 2)
            cv2.circle(frame, (cX, cY), 5, (0, 0, 255), -1)

        colored_mask = np.zeros_like(frame, dtype=np.uint8)
        colored_mask[mask > 0] = [255, 0, 0] # BGR
        frame = cv2.addWeighted(frame, 1, colored_mask, 0.4, 0)

    for i in range(1, len(trajectory_points)):
        cv2.line(frame, trajectory_points[i - 1], trajectory_points[i], (0, 255, 255), 2)

    out_video.write(frame)
    frame_idx += 1

cap.release()
out_video.release()
print(f" ویدیوی نهایی با موفقیت ذخیره شد:\n{output_video_path}")



# رسم نمودار پراکندگی مسیر حرکت

import matplotlib.pyplot as plt
import numpy as np

output_plot_path = '/content/drive/My Drive/DIP_FinalProject/Eagle_Trajectory_Plot.png'

if len(centroids_x) > 0:
    plt.figure(figsize=(10, 6))


    times = np.arange(len(centroids_x))
    scatter = plt.scatter(centroids_x, centroids_y, c=times, cmap='plasma', marker='o', s=40, edgecolor='k')

    cbar = plt.colorbar(scatter)
    cbar.set_label('Frame Number (Time)')


    plt.plot(centroids_x, centroids_y, color='gray', linestyle='--', alpha=0.5)

    plt.title('2D Trajectory of the Eagle in Flight', fontsize=14, fontweight='bold')
    plt.xlabel('X Coordinate (Pixels)', fontsize=12)
    plt.ylabel('Y Coordinate (Pixels)', fontsize=12)

    plt.gca().invert_yaxis()
    plt.grid(True, linestyle=':', alpha=0.7)

    plt.savefig(output_plot_path, dpi=300, bbox_inches='tight')
    print(f"نمودار مسیر حرکت ذخیره شد:\n{output_plot_path}")
    plt.show()
else:
    print(" هیچ مسیری یافت نشد. به نظر می‌رسد مدل نتوانسته شیء را در ویدیو شناسایی کند.")

